//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DTFM_Generator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DTFM_GENERATOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SETTINGS             141
#define IDD_DIALOG_ASIO_CONNECT         142
#define IDR_MENU_MAIN                   144
#define IDC_DIGIT                       1001
#define IDC_TEXT                        1010
#define IDC_PLAY_STRING                 1014
#define IDC_EDIT_BUFFER_SIZE            1014
#define IDC_ABORT                       1015
#define IDC_EDIT_SCALE                  1016
#define IDC_EDIT_ASIO_DEVICE            1017
#define IDC_EDIT_SIZE_ASIO_BUFFER       1018
#define IDC_AMPLITUDE                   1019
#define IDC_EDIT_GARMONIC_5             1020
#define IDC_EDIT_GARMONIC_6             1021
#define IDC_DO                          1022
#define IDC_EDIT_ATTACK                 1022
#define IDC_EDIT_REZ_MIN                1022
#define IDC_RE                          1023
#define IDC_EDIT_REZ_MAX                1023
#define IDC_ME                          1024
#define IDC_FA                          1025
#define IDC_SOL                         1026
#define IDC_LA                          1027
#define IDC_SI                          1028
#define IDC_DO_DIES                     1029
#define IDC_RE_DIES                     1030
#define IDC_FA_DIES                     1031
#define IDC_SOL_DIES                    1032
#define IDC_LA_DIES                     1033
#define IDC_DO2                         1034
#define IDC_RE2                         1035
#define IDC_ME2                         1036
#define IDC_FA2                         1037
#define IDC_SOL2                        1038
#define IDC_DO2_DIES                    1039
#define IDC_RE2_DIES                    1040
#define IDC_FA2_DIES                    1041
#define IDC_OCTAVE                      1042
#define IDC_BORDER                      1043
#define IDC_EDIT1                       1044
#define IDC_SLIDER1                     1045
#define IDC_SLIDER2                     1046
#define IDC_SLIDER3                     1047
#define IDC_SLIDER4                     1048
#define IDC_SLIDERM2                    1049
#define IDC_SLIDERM3                    1050
#define IDC_SLIDERM4                    1051
#define IDC_BUTTON_MIDI_OPEN            1052
#define IDC_BUTTON_MIDI_CLOSE           1053
#define IDC_EDIT_MIDI_OPEN              1054
#define IDC_BUTTON_WRITE                1055
#define IDC_BUTTON_WRITE_STOP           1056
#define IDC_BUTTON_PLAY_WRITEN          1057
#define IDC_BUTTON_RESET                1058
#define IDC_SLIDER5                     1059
#define IDC_CLOSE                       1060
#define IDC_BUTTON_ASIO_CONTROL_PANEL   1060
#define IDC_STOP_PLAY                   1061
#define IDC_HIDE                        1062
#define IDC_BUTTON_RND_GARMONIC         1062
#define IDC_EDIT_MIDI_NAME              1063
#define IDC_EDIT_STATUS_TEXT            1063
#define IDC_SLIDER6                     1064
#define IDC_EDIT_FREQ                   1065
#define IDC_BUTTON1                     1066
#define IDC_SLIDERM5                    1066
#define IDC_SLIDER_DECREMENT            1067
#define IDC_SLIDERM6                    1068
#define IDC_EDIT_MIDI_NAME2             1069
#define IDC_EDIT_SLIDER_DECREMENT       1070
#define IDC_EDIT_BASE_A                 1071
#define IDC_BUTTON_BREAK                1072
#define IDC_EDIT_WAVE_LEN               1072
#define IDC_SLIDER_TOTAL_VOLUME         1073
#define IDC_EDIT_MODULATION             1074
#define IDC_EDIT_MODULATION_WHEEL       1075
#define IDC_CHECK_USE_MODULATION        1076
#define IDC_EDIT_ASIO_DEVICE_INDEX      1077
#define IDC_EDIT_MODULATION_FREQ        1077
#define IDC_EDIT_SAMPLE_RATE            1078
#define IDC_EDIT_PIANOROLL              1079
#define IDC_LEVEL_CONTROL               1080
#define IDC_CHECK_GARMONIC_5_OFF        1081
#define IDC_CHECK_GARMONIC_6_OFF        1082
#define IDC_CHECK_GARMONIC_1_OFF        1083
#define IDC_CHECK_GARMONIC_2_OFF        1084
#define IDC_CHECK_GARMONIC_3_OFF        1085
#define IDC_CHECK_GARMONIC_4_OFF        1086
#define IDC_CHECK_GARMONIC_M6_OFF       1087
#define IDC_CHECK_GARMONIC_M5_OFF       1088
#define IDC_CHECK_GARMONIC_M4_OFF       1089
#define IDC_CHECK_GARMONIC_M3_OFF       1090
#define IDC_CHECK_GARMONIC_M2_OFF       1091
#define IDC_EDIT_FILL_BUFFER_TICKCOUNT  1092
#define IDC_REMEMBER                    1093
#define IDC_CHECK_USE_VELOCITY          1094
#define IDC_CHECK_NO_SUSTAIN            1095
#define IDC_CHECK_PIANO_MOUSE_CLICK     1096
#define IDC_CHECK_CTRL_KEY              1097
#define IDC_STATIC_CSLIDER1             1098
#define IDC_STATIC_CSLIDER2             1099
#define IDC_BUTTON_DEMO                 1100
#define IDC_STATIC_CSLIDER3             1101
#define IDC_STATIC_CSLIDER4             1102
#define IDC_STATIC_CSLIDER5             1103
#define IDC_CHECK_SAW                   1104
#define IDC_CHECK_FILTER_OFF            1105
#define IDC_CHECK_WRITE_RAWDATA_PCM     1106
#define IDC_STATIC_CSLIDER6             1107
#define IDC_STATIC_CSLIDER7             1108
#define IDC_CHECK_FILTER2               1109
#define IDC_BUTTON_SAVE_GARMONICS       1110
#define IDC_BUTTON_LOAD_GARMONICS       1111
#define IDC_BUTTON_PLUS_XSCALE_WAVEGRAPHIC 1112
#define IDC_BUTTON_MINUS_XSCALE_WAVEGRAPHIC 1113
#define ID_FILE_EXIT                    32771
#define ID_SETTINGS_SETASIODEVICE       32772
#define ID_KEYBOARD_KEYS_MENU           32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
